"""Stable fail-closed reason codes for company-agent governance."""

from __future__ import annotations

LEGAL_MATTER_SCOPE_REQUIRED = "LEGAL_MATTER_SCOPE_REQUIRED"
LEGAL_MATTER_SCOPE_MISMATCH = "LEGAL_MATTER_SCOPE_MISMATCH"
LEGAL_CONTRACT_OUTSIDE_SCOPE = "LEGAL_CONTRACT_OUTSIDE_SCOPE"
LEGAL_CROSS_MATTER_AUTHORITY_REQUIRED = "LEGAL_CROSS_MATTER_AUTHORITY_REQUIRED"

ACCOUNTS_AMOUNT_INVALID = "ACCOUNTS_AMOUNT_INVALID"
ACCOUNTS_AMOUNT_NON_FINITE = "ACCOUNTS_AMOUNT_NON_FINITE"
ACCOUNTS_AMOUNT_NON_POSITIVE = "ACCOUNTS_AMOUNT_NON_POSITIVE"
ACCOUNTS_AMOUNT_OVER_LIMIT = "ACCOUNTS_AMOUNT_OVER_LIMIT"
ACCOUNTS_CURRENCY_UNSUPPORTED = "ACCOUNTS_CURRENCY_UNSUPPORTED"
ACCOUNTS_INVOICE_MISMATCH = "ACCOUNTS_INVOICE_MISMATCH"
ACCOUNTS_BENEFICIARY_MISMATCH = "ACCOUNTS_BENEFICIARY_MISMATCH"

PROCUREMENT_VENDOR_UNKNOWN = "PROCUREMENT_VENDOR_UNKNOWN"
PROCUREMENT_VENDOR_UNREGISTERED = "PROCUREMENT_VENDOR_UNREGISTERED"
PROCUREMENT_MATERIAL_UNKNOWN = "PROCUREMENT_MATERIAL_UNKNOWN"
PROCUREMENT_RFQ_VENDORS_INVALID = "PROCUREMENT_RFQ_VENDORS_INVALID"
PROCUREMENT_QUOTE_MISSING = "PROCUREMENT_QUOTE_MISSING"
PROCUREMENT_QUOTE_MISMATCH = "PROCUREMENT_QUOTE_MISMATCH"
PROCUREMENT_REQUISITION_MISSING = "PROCUREMENT_REQUISITION_MISSING"
PROCUREMENT_RFQ_IDEMPOTENCY_CONFLICT = "PROCUREMENT_RFQ_IDEMPOTENCY_CONFLICT"

__all__ = [
    "ACCOUNTS_AMOUNT_INVALID",
    "ACCOUNTS_AMOUNT_NON_FINITE",
    "ACCOUNTS_AMOUNT_NON_POSITIVE",
    "ACCOUNTS_AMOUNT_OVER_LIMIT",
    "ACCOUNTS_BENEFICIARY_MISMATCH",
    "ACCOUNTS_CURRENCY_UNSUPPORTED",
    "ACCOUNTS_INVOICE_MISMATCH",
    "LEGAL_CONTRACT_OUTSIDE_SCOPE",
    "LEGAL_CROSS_MATTER_AUTHORITY_REQUIRED",
    "LEGAL_MATTER_SCOPE_MISMATCH",
    "LEGAL_MATTER_SCOPE_REQUIRED",
    "PROCUREMENT_MATERIAL_UNKNOWN",
    "PROCUREMENT_QUOTE_MISMATCH",
    "PROCUREMENT_QUOTE_MISSING",
    "PROCUREMENT_REQUISITION_MISSING",
    "PROCUREMENT_RFQ_IDEMPOTENCY_CONFLICT",
    "PROCUREMENT_RFQ_VENDORS_INVALID",
    "PROCUREMENT_VENDOR_UNKNOWN",
    "PROCUREMENT_VENDOR_UNREGISTERED",
]
